import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Heroes — Virtual Challenges Across Japan',
    short_name: 'Heroes',
    description:
      'Purpose-built virtual challenges across Japan. Every finish delivers a premium medal and plants a tree.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0F1114',
    theme_color: '#375E65',
    categories: ['health', 'fitness', 'lifestyle', 'sports'],
    icons: [
      // Browser-tab favicon (kept for legacy clients).
      {
        src: '/favicon.ico',
        sizes: '48x48',
        type: 'image/x-icon',
      },
      // Generated by app/icon.tsx — Android home screen + Lighthouse PWA installable check.
      {
        src: '/icon/192',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon/192',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/icon/512',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon/512',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
